FROM ubuntu:latest
RUN apt-get update && apt-get install -y mariadb-client
# install nushell from https://github.com/nushell/nushell/releases/download/0.91.0/nu-0.91.0-x86_64-unknown-linux-gnu.tar.gz
WORKDIR /root
RUN apt-get install -y wget
RUN wget https://github.com/nushell/nushell/releases/download/0.91.0/nu-0.91.0-x86_64-unknown-linux-gnu.tar.gz
RUN tar -xvf nu-0.91.0-x86_64-unknown-linux-gnu.tar.gz

COPY ./app /app
COPY ./start.nu /app/start.nu
RUN cp /root/nu-0.91.0-x86_64-unknown-linux-gnu/nu /app/nu
WORKDIR /app

CMD [ "./nu" , "start.nu"]